import Head from 'next/head'
import React from 'react'

import { Inter } from '@next/font/google'
import '../styles/Home.module.css'
import Introduction from '../components/Introduction'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
	faSun,
	faMoon,
	faHome,
	faUser,
	faEnvelopeOpen,
	faPen,
	faLightbulb,
} from '@fortawesome/free-solid-svg-icons'

const inter = Inter({ subsets: ['latin'] })

interface HomeProps {}

interface HomeState {
	title: string
	activeSlideIndex: number
	currentTheme: string
}

class Home extends React.Component<HomeProps, HomeState> {
	state = {
		title: 'Abhay Singh',
		activeSlideIndex: 0,
		currentTheme: 'dark',
	}

	setTheme(theme: string) {
		const html = document.querySelector('html')
		localStorage.setItem('theme', theme)
		html?.setAttribute('data-theme', theme)
		this.setState({
			...this.state,
			currentTheme: theme,
		})
	}

	links = [
		{
			icon: faHome,
			slideIndex: 0,
			onSMScreen: true,
			onLGScreen: true,
			title: 'Home',
		},
		{
			icon: faUser,
			slideIndex: 1,
			onSMScreen: true,
			onLGScreen: true,
			title: 'About',
		},
		{
			icon: faPen,
			slideIndex: 2,
			onSMScreen: true,
			onLGScreen: true,
			title: 'Skills',
		},
		{
			icon: faEnvelopeOpen,
			slideIndex: 3,
			onSMScreen: true,
			onLGScreen: true,
			title: 'Connect',
		},
	]

	componentDidMount(): void {
		const storageTheme = localStorage.getItem('theme')
		if (storageTheme?.length) {
			this.setTheme(storageTheme)
		} else {
			this.setTheme(this.state.currentTheme)
		}
	}

	render() {
		return (
			<>
				<Head>
					<title>{this.state.title}</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className="overflow-y-auto max-h-screen bg-base-300">
					<div className="accent-pyramid border-primary"></div>
					<div className="absolute right-0 mt-3 mr-6 z-50">
						<button
							onClick={() => {
								this.setTheme(
									this.state.currentTheme === 'dark' ? 'light' : 'dark',
								)
							}}
							className="btn flex w-12 h-12 rounded-full items-center justify-center"
						>
							<FontAwesomeIcon
								icon={this.state.currentTheme === 'dark' ? faLightbulb : faMoon}
								className="w-6 h-6 cursor-pointer"
							/>
						</button>
					</div>
					<nav>
						<div className="btm-nav z-40 lg:hidden">
							{this.links.map((obj, index) =>
								obj.onSMScreen ? (
									<a
										className={
											'text-primary ' +
											(this.state.activeSlideIndex === obj.slideIndex
												? 'active'
												: '')
										}
										key={index}
										href={'#page' + obj.slideIndex}
									>
										<FontAwesomeIcon icon={obj.icon} className="w-6 h-6" />
									</a>
								) : (
									<></>
								),
							)}
						</div>
					</nav>
					<nav className="fixed z-40 right-0 hidden lg:flex min-h-screen items-center p-3">
						<ul className="menu gap-4 p-2 rounded-box h-1/2 ">
							{this.links.map((obj, index) =>
								obj.onLGScreen ? (
									<li
										key={index}
										className="group flex items-end text-primary-content"
									>
										<a
											className={
												'btn group-hover:bg-primary-focus transition-all duration-300' +
												' ' +
												(this.state.activeSlideIndex === obj.slideIndex
													? 'bg-primary'
													: '')
											}
											// style={{
											// 	borderRadius: '50%',
											// }}
											href={'/#page' + obj.slideIndex}
										>
											<span className="uppercase tracking-wider hidden group-hover:flex ">
												{obj.title}{' '}
											</span>{' '}
											<FontAwesomeIcon icon={obj.icon} className="w-4 h-4" />
										</a>
									</li>
								) : (
									<></>
								),
							)}
						</ul>
					</nav>
					<section>
						<div id="page0">
							<Introduction />
						</div>
						<div id="page1" className="bg-base-100">
							<Introduction />
						</div>
						<div id="page2">
							<Introduction />
						</div>
						<div id="page3" className="bg-base-100">
							<Introduction />
						</div>
					</section>
				</main>
			</>
		)
	}
}

export default Home
